project_id = "xnppcugncigaiycrvmpk"

[functions.stripe-webhook]
verify_jwt = false

[functions.activate-license]
verify_jwt = false

[functions.validate-license]
verify_jwt = false

[functions.usage-ping]
verify_jwt = false

[functions.public-metrics]
verify_jwt = false
